/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_mariapadilla;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author belen
 */
public class Supermecado extends javax.swing.JFrame {
 Scanner sc = new Scanner(System.in);

    /**
     * Creates new form Supermecado
     */
    public Supermecado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jT_c = new javax.swing.JTextField();
        jB_Enter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_File = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jM_Window = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jM_Help = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Category", "Price", "Aisle", "Bin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("CSVs");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        jT_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_cActionPerformed(evt);
            }
        });

        jB_Enter.setText("Enter");
        jB_Enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_EnterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jT_c, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_c, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Enter))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap())
        );

        jM_File.setText("File");

        jMenuItem1.setText("New File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jM_File.add(jMenuItem1);

        jMenuItem2.setText("Import File");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jM_File.add(jMenuItem2);

        jMenuBar1.add(jM_File);

        jM_Window.setText("Window");

        jMenu1.setText("Clear");

        jMenuItem3.setText("Clear Command Line");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Clear Table");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jM_Window.add(jMenu1);

        jMenuItem4.setText("Refresh Tree");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jM_Window.add(jMenuItem4);

        jMenuBar1.add(jM_Window);

        jM_Help.setText("Help");

        jMenuItem7.setText("Product Structure");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jM_Help.add(jMenuItem7);

        jMenuItem6.setText("Commands");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jM_Help.add(jMenuItem6);

        jMenuBar1.add(jM_Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here
         if (jT_c.getText().equals("./data.txt")){
            CargarTabla();
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jT_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_cActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jT_cActionPerformed

    private void jB_EnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_EnterMouseClicked
        // TODO add your handling code here:
        if (jT_c.getText().equals("./data.txt")){
            CargarTabla();
            
        }
        if (jT_c.getText().equals("./create archivo.txt")){
            try {
                CreacionArchivos();
            } catch (IOException ex) {
                Logger.getLogger(Supermecado.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        if (jT_c.getText().equals("./clear")){
             eliminar();
        
        } if (jT_c.getText().equals("./refresh")){
            arboles();
        }
           
        
    }//GEN-LAST:event_jB_EnterMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            // TODO add your handling code here:
         if (jT_c.getText().equals("./create archivo.txt")){
           try {
               CreacionArchivos();
          
          } catch (IOException ex) {
                Logger.getLogger(Supermecado.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jT_c.setText(" ");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       // TODO add your handling code here:
       if (jT_c.getText().equals("./clear")){
             eliminar();
        
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if (jT_c.getText().equals("./refresh")){
            arboles();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Id: es el numero identificador del objeto\n"
                + "name: nombre del producto\n"
                + "Category: es la categoria\n"
                + "Price: Valor del producto\n"
                + "Aisle:numero de pasillo donde se encuentra\n"
                + "Bin: es la repiusa del producto\n");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"lista de comandos:\n"
                + "./data.txt\n"
                + "./create archivo.txt\n"
                + "./clear\n"
                + "./refresh\n");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supermecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supermecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supermecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supermecado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supermecado().setVisible(true);
            }
        });
    }
    // metodos
    public void CargarTabla (){
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        DefaultTableModel modelo =(DefaultTableModel )jTable1.getModel();
        
        try {
             archivo = new File("./data.txt"); 
             sc = new Scanner(archivo);
             while (sc.hasNext()) {
                String next = sc.nextLine();
                System.out.println(next);
                String []tok=next.split(",");
                Object []m={tok[0],tok[1],tok[2],tok[3],tok[4],tok[5]};
                modelo.addRow(m);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    public void CreacionArchivos () throws IOException{
//        DefaultTableModel modelo =(DefaultTableModel )jTable1.getModel();
//        AdmiProducto admi=new AdmiProducto("./prueba.txt");
//       
//        for (int i = 0; i < modelo.getRowCount(); i++) {
//            System.out.println(modelo.getValueAt(i, 0));
//            System.out.println(modelo.getValueAt(i, 1));
//            System.out.println(modelo.getValueAt(i, 2));
//            System.out.println(modelo.getValueAt(i, 3));
//            System.out.println(modelo.getValueAt(i, 4));
//            System.out.println(modelo.getValueAt(i, 5));
//            
//            
//            int id=(int) modelo.getValueAt(i,0 );
//            String name= modelo.getValueAt(i,1 ).toString();
//            int cate= (int) modelo.getValueAt(i,2 );
//            double price=(double) modelo.getValueAt(i,3 );
//            int aisle=  Integer.parseInt(modelo.getValueAt(i,4 ).toString()) ;
//            double bin=(double) modelo.getValueAt(i,5 );
//            Producto p=new Producto(id,name,cate,price,aisle,bin);
//            System.out.println(p.toString());
//            admi.getListaProductos().add(p);
//            System.out.println(id);
//            
//            
//        }
//        //System.out.println(admi.getListaProductos());
//        admi.escribirArchivo();
//    
///te queda de evidencia :(

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        String acum = "";
       // AdmiProducto admi=new AdmiProducto("./prueba.txt");
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            String l = jT_c.getText();
            String[] parse = l.split(" ");
            archivo = new File("./" + parse[1]);
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            for (int i = 0; i < modelo.getRowCount(); i++) {
                for (int j = 0; j < modelo.getColumnCount(); j++) {
                    if (modelo.getValueAt(i, j) != null) {
                        modelo.getValueAt(i, j);
                        acum += modelo.getValueAt(i, j) + ",";
                    }
                }
                bw.write(acum);
                acum = "";
            }
            bw.newLine();
            bw.flush();
        } catch (Exception e) {
        }
        bw.close();
        fw.close();
    }
    public void eliminar (){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int tabla=modelo.getRowCount();
            for (int j = 0; j< tabla; j++) {
                modelo.removeRow(0);    
            }
      
        modelo.setRowCount(1);
        
    
    }
    public void arboles (){
        File archivo = new File(".");
        File f[] = archivo.listFiles();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root"); 
        DefaultTreeModel modeloARBOL = new DefaultTreeModel(root);
        //modeloARBOL.setRoot(root);
        for (File file : f) {
            if (file.getName().contains(".txt")) {
                DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(file.getName());
                root.add(nodo); 
                System.out.println("entras");
            }
        }
        jTree1.setModel(modeloARBOL);
        modeloARBOL.reload(); 
    
    
    
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Enter;
    private javax.swing.JMenu jM_File;
    private javax.swing.JMenu jM_Help;
    private javax.swing.JMenu jM_Window;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jT_c;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
